services:
  details-dev:
    build: .
    image: ghcr.io/violet-evergardenz/bookinfo-details:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
  details-uat:
    build: .
    image: ghcr.io/violet-evergardenz/bookinfo-details:uat
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
  details-prd:
    build: .
    image: ghcr.io/violet-evergardenz/bookinfo-details:prd
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2