apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.details.namespace }}
spec:
  type: {{ .Values.ingress.ServiceType }}
  ports:
  - port: {{ .Values.details.port }}
  selector:
    app: {{ .Release.Name }}